package banking;

public enum ProcessState {
    POWER_ON,
    POWER_OFF,
    MAIN_MENU,
    ACCOUNT_MENU,
    CHOOSE_MAIN_MENU_ACTION,
    CHOOSE_ACCOUNT_MENU_ACTION,
    CREATE_CREDIT_CARD_ACCOUNT,
    LOG_INTO_ACCOUNT,
    LOG_OUT_ACCOUNT,
    SHOW_BALANCE,
    ADD_INCOME,
    DO_TRANSFER,
    CLOSE_ACCOUNT;
}
